language: python
python:
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r requirements/common.txt
  - npm install
  - bower install
  - gulp
  - ./manage.py migrate --noinput
  - ./manage.py loaddata config/adminuser.json
script:
  # Integration tests
  - ./manage.py test website


