language: python
python:
  - "2.6"
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r requirements/common.txt
script:
  # Normal tests
  - fab test
  - fab devupdate
  # Integration tests
  - ./manage.py test website


