language: python
python:
  - "2.6"
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r requirements/common.txt
  # Get fab to test fab
  - pip install -e .
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - "pip install jinja2"
script:
  # Normal tests
  - fab test
  - fab devupdate
  # Integration tests
  - ./manage.py test website

